### PR TITLE
Fix knockback misscalculation

### LINKED ISSUE #11: [Bug]: Knockback miscalculation.
### Describe the Bug

when you gently touch other entity from other side of the world / behind the border entity gets knocked back to you instead of further from you

### Mod version(s) affected

1.0.2

### Mod loader(s) used

Fabric

### Minecraft version(s) used

1.20.4

### Other mods used

_No response_

### To Reproduce (If applicable)

1. Go to the world border
2. Spawn some entity
3. Go to the other side of border
4. Gently touch the entity

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Skidamek**
Fixes #11
Also updated fabric loader to get newer mixin extras with wrapmethod injector

### CODE REVIEW

**Comment by FamroFexl** [comment]
Actually, you can get the actual distance to an entity by unwrapping a coord1 relative to a coord2. This puts the coord2 in the same coordinate space as the coord1, so the actual distance operation you implemented isn't necessary.

Just do `double coord3 = xTransformer.unwrapCoordFromLimit(coord2, coord1)` and run a distance check on the result from `coord2` to `coord3`

I re-implemented it with `getMinimumDistBetween`

**Comment by FamroFexl** [comment]
You should check your changes to `FishingHookMixin`. While the fishing rod pulls in the right direction, when I try to fling a pig into the air by hooking it from above, it resists my pulling. This also occurs with lateral movement.

**Review by FamroFexl — CHANGES_REQUESTED** [review]
You should check your changes to `FishingHookMixin`. While the fishing rod pulls in the right direction, when I try to fling a pig into the air by hooking it from above, it resists my pulling. This also occurs with lateral movement.

**Comment by Skidamek** [comment]
Fixed, however seems like your commit broke directions. For me it now pulls entities in wrong directions.
It may be section dependent, check behind different borders. (And see discord...)

**Comment by FamroFexl** [comment]
I printed out both our methods, and they are identical in output numbers, except that yours outputs negative numbers sometimes, which seems like a bug for a distance formula.

**Comment by Skidamek** [comment]
Well maybe the method name is misleading but there should be negatives some times I think, if not then that would mean that entities could be only knocked in two directions +x and +z but surely you should can pull it to -x and -z, or am I wrong?

**Review by FamroFexl — APPROVED** [review]
It appears that it was a delta, not a distance, so I changed my method accordingly.

**Comment by Skidamek** [comment]
Perfect 👌 thanks

**Pull request merged**
