### PR TITLE
Fix not being able to place buckets on blocks from behind the bounds

### PR DESCRIPTION
**Pull request by Skidamek**
Yep not sure why this class needs to have fix on `use` method from parent `Item` class while `BlockItem` class does similar calculations and it even doesn't override that method anyway that fixes placing buckets of fluids on blocks from behind the bounds - I didn't want to dig much into code, you probably know it better since you wrote code which allows to place blocks out of bounds, i dont mind if this is wrong way of fixing it, feel free to do your own thing.

Current issues i found are players' hand not doing the place motion when placing outside of bounds and sound not playing (at least on client which places the bucket) when placing outside of bounds

### CODE REVIEW

**Comment by FamroFexl** [comment]
I just did a general update that wrapped the `Level.setBlock` method, and that appeared to fix all placement issues in totality. (see here https://github.com/FamroFexl/Circumnavigate/blob/develop/src/main/java/com/fexl/circumnavigate/mixin/entityHandle/collisions/LevelMixin.java)

**Comment by FamroFexl** [comment]
> I just did a general update that wrapped the `Level.setBlock` method, and that appeared to fix all placement issues in totality. (see here https://github.com/FamroFexl/Circumnavigate/blob/develop/src/main/java/com/fexl/circumnavigate/mixin/entityHandle/collisions/LevelMixin.java)

Even got rid of `BlockItemMixin`

**Comment by Skidamek** [comment]
Sheesh dope! and you got rid of 2/3 of my fluid mixins bruh - ~~well it makes sense since process of that mixin was writing methods until it starts working so the last method was the most important~~ that one is even a different method never mind, cool that you uncomplicated it so much

**Comment by FamroFexl** [comment]
> Sheesh dope! and you got rid of 2/3 of my fluid mixins bruh - well it makes sense since process of that mixin was writing methods until it starts working so the last method was the most important

see discord

**Pull request closed without merging**
