### PR TITLE
Compute wrapped chunk tickets by our own

### LINKED ISSUE #10: [Bug]: Piston updates aren't sent to wrapped players.
### Describe the Bug

Pistons on one side of the wrapping border aren't updated for players on the other side of the wrapping border unless another player is present in the piston's chunk.

### Mod version(s) affected

1.0.2

### Mod loader(s) used

Fabric

### Minecraft version(s) used

1.20.4

### Other mods used

_No response_

### To Reproduce (If applicable)

Place a piston on one side of the world with a lever connected to it. Go to the other side of the world and activate it several times. You will see the piston stops responding to lever clicks client-side. Now have another player join and stand in the chunk where the piston is. If you activate the lever a few more times, you will see it is now updated properly client-side.

### Additional Information

I believe this might be an issue caused by chunk loading levels not being properly updated for past-bounds chunks. However, as of yet I have been unable to track down what code needs to be changed in `ChunkTracker` and its sub-classes specifically.

### PR DESCRIPTION
**Pull request by Skidamek**
Added `WrappedChunks` class per level, which calculates and manages chunk tickets for wrapped chunks.
Chunk ticket updates are called by `DistanceManagerMixin`. All tickets are level 31 (everything should be processed each tick) see [minecraft wiki](https://minecraft.wiki/w/Chunk#Level_and_load_type), theres also some code which calculates lower levels but it doesnt really change anything (wiki) so at the time being it is used to sort chunks if its near player it should load faster due to ticket being made first.
Not sure why i made it thread safe, you can change it.

Implementation is no near perfect yet and will require further maintenance, however it already works pretty well.

Fixes #10

### CODE REVIEW

**Comment by FamroFexl** [comment]
Um, I have definitely seen loading levels from 0-31 quite regularly in my debug testing. Not sure what the minecraft wiki is on about... I'm not sure if it matters generally, but using higher loading levels (closer to 0) might make more important chunks (closer to the player) work properly even if the server is stressed (higher loading levels are prioritized for processing first).

I don't have time to get to it today, but do you know of any issues so far? In general the problems from this bug stem from two players being in a border chunk at once, and one of the players entering and leaving an adjacent chunk on the other side. Has that been tested in your implementation?

**Comment by FamroFexl** [comment]
I'm also not that keen on replacing a whole chunk loading system when I am unsure of how the original system works...

**Comment by Skidamek** [comment]
> Um, I have definitely seen loading levels from 0-31 quite regularly in my debug testing. Not sure what the minecraft wiki is on about... I'm not sure if it matters generally, but using higher loading levels (closer to 0) might make more important chunks (closer to the player) work properly even if the server is stressed (higher loading levels are prioritized for processing first).

That would be quite simple to implement since we already calculating the loading levels

> I don't have time to get to it today, but do you know of any issues so far? In general the problems from this bug stem from two players being in a border chunk at once, and one of the players entering and leaving an adjacent chunk on the other side. Has that been tested in your implementation?

Yes i tried to recreate this bug like showed in the video, no issues so far.

> I'm also not that keen on replacing a whole chunk loading system when I am unsure of how the original system works...

We are not replacing it at all, we just force game to load chunks we need. Replacing whole chunk loading system would be much more complex see c2me or moonrise mods

**Comment by Skidamek** [comment]
To be honest i really believe this approach is quite good (just implementation is not complete / exactly right) but i mean we don't need to have complex mixins which could break while updating to any new version and we dont need to worry about mod compat. Force loading chunks like this is known practice even supported by mojang them selves there's vanilla /forceload command which just does exactly what we do there with one change that we actually track players and unload chunks which are not needed. KISS - Keep it simple, stupid!

**Comment by FamroFexl** [comment]
When you talk about complex mixins breaking in-between version updates, I don't think that's a problem as there are almost no complex mixins in this mod. (there are a few method copy-paste jobs, but those are mostly so I can make additional modifications to them in the future if needed. That's why I haven't summarized the `handleMovePlayer` mixin, for example). Most of the time spent on this mod goes into finding the best places to put mixins so that they are effective, scarce, and non-intrusive. The mixins themselves are mostly just coordinate manipulators operating on different types of coordinate containers (like `ChunkPos`, `Vec3`, and `BlockPos`). 

If the mixins break between Minecraft versions, it’s more beneficial to understand why they broke so we can address any potential new issues, rather than relying on a new system that never breaks but remains ignorant of its underlying foundation. If the foundation shifts, and your system is insulated from those shifts, it will be hard to investigate what needs to be changed in your system because you are not part of the foundation system. That is why I am more fond of integrating with the vanilla systems as much as possible, rather than creating our own systems. Working through the problem is much better than working around the problem.

I believe that mod compatibility will be best supported if all our changes are under the hood and operate behind the scenes seamlessly. Mods that use the underlying systems in a similar fashion will be supported by default. That is why integration with the existing system is much better than working around the system.

The fact that Mojang provides the `forceload` command does not mean they condone using it themselves. They don't even use it within minecraft's own code to my knowledge. It is a utility command and a means to solve issues caused by chunk loading messing up redstone contraptions.

My attitude towards this mod and it's design is composed of targeted and tightly integrated modifications that appear seamless to casual and particular observers. Small changes, big effect. I don't just want to solve the issue and move on, because the solution might become a problem in the future. Since we aren't in any hurry to get this mod production-ready, I would rather do it right the first time then have to deal with code debt from hacky or quick-and-dirty solutions in the future.

With all that being said, I'm going to put this PR on hold for the time being. I don't want another chunk loading system in parallel with the vanilla system. I want to make sure that the vanilla system is fully incapable of accommodating the needs of this issue before proceeding. I would rather attempt to cooperate with the existing chunk loading system before creating another system that bypasses it. For now, I am not convinced the vanilla system is incapable of fulfilling these needs, mainly because I am still largely ignorant of the vanilla system's inner workings. If I find that the vanilla system will not accommodate a simple solution to this issue, then I will reconsider your solution. I hate to be a didactic stickler about the whole issue, but I just believe this is the best path forward.

**Comment by FamroFexl** [comment]
> I hate to be a didactic stickler about the whole issue, but I just believe this is the best path forward.

Also, I prefer to get all my thoughts out at once so I can reference back to them when explaining why I made future or past decisions.

**Comment by Skidamek** [comment]
Perfect, I agree it would also has it's benefit in probably better performance. However since  in this pull request we rely on higher level system doing it this way makes it less vulnerable for changes in underlaying system, than injecting directly into underlaying system which could completely change and your great method which was done once but right could just break.

Anyway then I would advise to update already to 1.21.1 or 1.21.3 to minimalize such risks since already there were some changes to chunk system in 1.20.5.

**Comment by FamroFexl** [comment]
> your great method which was done once but right could just break.

The main effort required in getting the method to work was understanding the underlying system. If the system changes break the mixin, I consider it worthwhile to re-investigate the system to find out how it changed so we don't miss anything in our fix. If the changes are so fundamental that it requires a deep-dive into the new system, then it's likely that our higher level system wouldn't survive the new system's changes anyway.

**Comment by FamroFexl** [comment]
> I would advise to update already to 1.21.1 or 1.21.3 to minimalize such risks since already there were some changes to chunk system in 1.20.5.

I'm not sure what the advantage to that would be. Sure we could update our current mixins to the new versions, but on other mixins we haven't figured out yet (like this one), we would still be in the same situation. I think we should wait to update to newer versions until we have our core systems figured out (and have mixins applied to). Then we can use future versions to figure out nitty-gritty details like certain blocks or entities not working properly. I believe we are quite close to figuring out core systems.

**Comment by Skidamek** [comment]
Advantages are quite obvious, you would waste less time on porting to the newer version since likely you won't like to support 1.20.4 further anyway because it's less used than e.g. 1.21.1 and we would write mixins which already work on 1.21.1

**Comment by FamroFexl** [comment]
Alright, I'll work on a port to 1.21.1

**Pull request closed without merging**
